let anime = [{
    MovName:"Solo Leveling",
    year:'2025',
    image:'solo.jpg',
    rate:'4.7',
    hours:'21',
},
{
    MovName:"Squid Game",
    year:'2025',
    image:'SquidGame.jpg',
    rate:'4.5',
    hours:'21',
},
{
    MovName:"One Piece",
    year:'2025',
    image:'one_piece.jpg',
    rate:'4.6',
    hours:'21',
},
{
    MovName:"Demon City",
    year:'2025',
    image:"aime2.jpg",
    rate:'4.9',
    hours:' ',
},
{
    MovName:"Solo Leveling1",
    year:'2025',
    image:'anime1.jpg',
    rate:'4.7',
    hours:'21',
},
{
    MovName:"Naruto",
    year:'2025',
    image:"naruto.jpg",
    rate:'4.8',
    hours:' ',
},
{
    MovName:"Connection",
    year:'2025',
    image:"connection.jpg",
    rate:'4.3',
    hours:' ',
},
{
    MovName:"Hell Paradise",
    year:2025,
    image:'hell-paradise.jpg',
    rate:'4.4',
    hours:'21',
},
{
    MovName:"Jujutsu Kaisen",
    year:'2025',
    image:"jutsu.jpg",
    rate:'4.5',
    hours:' ',
},
{
    MovName:"Boruto",
    year:'2025',
    image:"boruto.jpg",
    rate:'4.9',
    hours:' ',
},
]
let trending = [{
    MovName:"Jujutsu Kaisen",
    year:'2025',
    image:"jutsu.jpg",
    rate:'4.8',
    hours:' ',
},
{
    MovName:"Squid Game",
    year:'2025',
    image:'SquidGame.jpg',
    rate:'4.0',
    hours:'21',
},
{
    MovName:"Naruto",
    year:'2025',
    image:"naruto.jpg",
    rate:'4.5',
    hours:' ',
},
{
    MovName:"Demonslayer",
    year:'2025',
    image:"demonslayer.avif",
    rate:'4.1',
    hours:' ',
},
{
    MovName:"Hell Paradise",
    year:2025,
    image:'hell-paradise.jpg',
    rate:'4.5',
    hours:'21',
},

{
    MovName:"Solo Leveling",
    year:'2025',
    image:'solo.jpg',
    rate:'4.2',
    hours:'21',   
},
]
let animeZ = [{
    MovName:"Naruto",
    year:'2025',
    image:"naruto.jpg",
    rate:'4.5',
    hours:' ',  
    
},
{
    MovName:"One Piece",
    year:'2025',
    image:'one_piece.jpg',
    rate:'4.3',
    hours:'21',
},
{
    MovName:"Hell Parasise",
    year:'2025',
    image:"hell-paradise.jpg",
    rate:'4.5',
    hours:' ',
},
{
    MovName:"Boruto",
    year:'2025',
    image:"boruto.jpg",
    rate:'4.4',
    hours:' ',
},
{
    MovName:"Jujutsu Kaisen",
    year:'2025',
    image:"jutsu.jpg",
    rate:'4.6',
    hours:' ',
   
},
{
    MovName:"Solo Leveling",
    year:'2025',
    image:'solo.jpg',
    rate:'4.8',
    hours:'21',
    
},
]